FROM node:20-alpine

WORKDIR /app

COPY frontend/web/package.json frontend/web/package-lock.json* ./
RUN npm install

COPY frontend/web ./

RUN npm run build

EXPOSE 3000
ENV PORT=3000

CMD ["npm", "run", "start"]
